version: 2.1

executors:
  amd64:
    machine:
      image: ubuntu-2004:202111-02
    resource_class: medium
  arm64:
    machine:
      image: ubuntu-2004:202111-02
    resource_class: arm.medium

platforms: &platforms
  - amd64
  - arm64

workflows:
  build_latest:
    jobs:
      - build:
          stream: latest
          context: docker-publishing
          matrix:
            parameters:
              executor: *platforms
      - manifest:
          stream: latest
          context: docker-publishing
          requires: [ build ]
          filters:
            branches:
              only: [ main ]

  build_stable:
    jobs:
      - build:
          stream: stable
          context: docker-publishing
          matrix:
            parameters:
              executor: *platforms
          filters:
            branches:
              only: [ releases ]
      - manifest:
          stream: stable
          context: docker-publishing
          requires: [ build ]
          filters:
            branches:
              only: [ releases ]

  nightly_latest:
    jobs:
      - build:
          stream: latest
          context: docker-publishing
          matrix:
            parameters:
              executor: *platforms
      - manifest:
          stream: latest
          context: docker-publishing
          requires: [ build ]
          filters:
            branches:
              only: [ main ]
    triggers:
      - schedule:
          # Scheduled build for 2am AEST nightly.
          cron: "0 15 * * *"
          filters:
            branches:
              only: [ main ]

  nightly_stable:
    jobs:
      - build:
          stream: stable
          context: docker-publishing
          matrix:
            parameters:
              executor: *platforms
          filters:
            branches:
              only: [ releases ]
      - manifest:
          stream: stable
          context: docker-publishing
          requires: [ build ]
          filters:
            branches:
              only: [ releases ]
    triggers:
      - schedule:
          # Scheduled build for 2am AEST nightly.
          cron: "0 15 * * *"
          filters:
            branches:
              only: [ releases ]

jobs:
  build:
    parameters:
      executor:
        type: string
      stream:
        type: string
    executor: << parameters.executor >>
    steps:
      - checkout
      - run:
          name: Build, Test and Release
          command: |
            SHA1_VERSION="v2-$(git rev-parse --short HEAD)"
            make build ARCH=<< parameters.executor >> FROM=docker.io/opensearchproject/opensearch:1.1.0 VERSION_TAG=v2-1.1.x
            make build ARCH=<< parameters.executor >> FROM=docker.io/opensearchproject/opensearch:1.2.4 VERSION_TAG=v2-1.2.x
            make build ARCH=<< parameters.executor >> FROM=docker.io/opensearchproject/opensearch:1.3.5 VERSION_TAG=v2-1.3.x
            make build ARCH=<< parameters.executor >> FROM=docker.io/opensearchproject/opensearch:1.3.5 VERSION_TAG=v2-<< parameters.stream >>
            make build ARCH=<< parameters.executor >> FROM=docker.io/opensearchproject/opensearch:2.18.0 VERSION_TAG=v2-2.x
      - when:
          condition:
            or:
              - equal: ["main", << pipeline.git.branch >> ]
              - equal: ["releases", << pipeline.git.branch >>]
          steps:
            - run:
                name: "Push image"
                command: |
                  echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
                  SHA1_VERSION="v2-$(git rev-parse --short HEAD)"
                  make push ARCH=<< parameters.executor >> VERSION_TAG=v2-<< parameters.stream >>
                  make push ARCH=<< parameters.executor >> VERSION_TAG=v2-1.1.x
                  make push ARCH=<< parameters.executor >> VERSION_TAG=v2-1.2.x
                  make push ARCH=<< parameters.executor >> VERSION_TAG=v2-1.3.x
                  make push ARCH=<< parameters.executor >> VERSION_TAG=v2-2.x
  manifest:
    parameters:
      stream:
        type: string
    docker:
      - image: cimg/base:2022.02
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Push Manifest
          command: |
            export DOCKER_CLI_EXPERIMENTAL=enabled
            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
            SHA1_VERSION="v2-$(git rev-parse --short HEAD)"
            make manifest VERSION_TAG=v2-<< parameters.stream >>
            make manifest VERSION_TAG=v2-1.1.x
            make manifest VERSION_TAG=v2-1.2.x
            make manifest VERSION_TAG=v2-1.3.x
            make manifest VERSION_TAG=v2-2.x
